###################################################################

# Created by write_sdc on Fri Jul  3 11:25:08 2026

###################################################################
set sdc_version 2.2

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_load -pin_load 0.05 [get_ports dispense]
set_load -pin_load 0.05 [get_ports {change_out[7]}]
set_load -pin_load 0.05 [get_ports {change_out[6]}]
set_load -pin_load 0.05 [get_ports {change_out[5]}]
set_load -pin_load 0.05 [get_ports {change_out[4]}]
set_load -pin_load 0.05 [get_ports {change_out[3]}]
set_load -pin_load 0.05 [get_ports {change_out[2]}]
set_load -pin_load 0.05 [get_ports {change_out[1]}]
set_load -pin_load 0.05 [get_ports {change_out[0]}]
set_load -pin_load 0.05 [get_ports error]
set_load -pin_load 0.05 [get_ports {display[7]}]
set_load -pin_load 0.05 [get_ports {display[6]}]
set_load -pin_load 0.05 [get_ports {display[5]}]
set_load -pin_load 0.05 [get_ports {display[4]}]
set_load -pin_load 0.05 [get_ports {display[3]}]
set_load -pin_load 0.05 [get_ports {display[2]}]
set_load -pin_load 0.05 [get_ports {display[1]}]
set_load -pin_load 0.05 [get_ports {display[0]}]
set_load -pin_load 0.05 [get_ports {state_out[2]}]
set_load -pin_load 0.05 [get_ports {state_out[1]}]
set_load -pin_load 0.05 [get_ports {state_out[0]}]
create_clock [get_ports clk]  -period 5  -waveform {0 2.5}
set_clock_uncertainty 0.5  [get_clocks clk]
set_input_delay -clock clk  3  [get_ports rst]
set_input_delay -clock clk  3  [get_ports confirm]
set_input_delay -clock clk  3  [get_ports cancel]
set_input_delay -clock clk  3  [get_ports {coin_in[1]}]
set_input_delay -clock clk  3  [get_ports {coin_in[0]}]
set_input_delay -clock clk  3  [get_ports {sel_item[1]}]
set_input_delay -clock clk  3  [get_ports {sel_item[0]}]
set_output_delay -clock clk  3  [get_ports dispense]
set_output_delay -clock clk  3  [get_ports error]
set_output_delay -clock clk  3  [get_ports {change_out[7]}]
set_output_delay -clock clk  3  [get_ports {change_out[6]}]
set_output_delay -clock clk  3  [get_ports {change_out[5]}]
set_output_delay -clock clk  3  [get_ports {change_out[4]}]
set_output_delay -clock clk  3  [get_ports {change_out[3]}]
set_output_delay -clock clk  3  [get_ports {change_out[2]}]
set_output_delay -clock clk  3  [get_ports {change_out[1]}]
set_output_delay -clock clk  3  [get_ports {change_out[0]}]
set_output_delay -clock clk  3  [get_ports {display[7]}]
set_output_delay -clock clk  3  [get_ports {display[6]}]
set_output_delay -clock clk  3  [get_ports {display[5]}]
set_output_delay -clock clk  3  [get_ports {display[4]}]
set_output_delay -clock clk  3  [get_ports {display[3]}]
set_output_delay -clock clk  3  [get_ports {display[2]}]
set_output_delay -clock clk  3  [get_ports {display[1]}]
set_output_delay -clock clk  3  [get_ports {display[0]}]
set_output_delay -clock clk  3  [get_ports {state_out[2]}]
set_output_delay -clock clk  3  [get_ports {state_out[1]}]
set_output_delay -clock clk  3  [get_ports {state_out[0]}]
set_drive 0.1  [get_ports rst]
set_drive 0.1  [get_ports {coin_in[1]}]
set_drive 0.1  [get_ports {coin_in[0]}]
set_drive 0.1  [get_ports {sel_item[1]}]
set_drive 0.1  [get_ports {sel_item[0]}]
set_drive 0.1  [get_ports confirm]
set_drive 0.1  [get_ports cancel]
